# play 1
- name: set up nginx
  # choose inventory group
  hosts: hosts
  # choose tasks to execute
  # every - is the start of a list
  tasks:
    - name: "apt-get update"
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: install on ubuntu
      # use sudo, root access
      become: yes
      apt: 
        name: nginx
        state: present
      # what state do who we want
      # present: install packages
      # absent: uninstall packages
      # check docs.ansible.com
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_module.html
    - name: copy index.html
      become: yes
      copy:
        src: index.html
        dest: /var/www/html/index.html
    - name: start nginx
      become: yes
      service:
        name: nginx
        state: started
        
  